# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "zenobia"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND", "CAPABILITY_NAMED_IAM"]
confirm_changeset = true
resolve_s3 = true
s3_prefix = "backend"
region = "us-east-1"
image_repositories = []
parameter_overrides = [
    # "UniqueIdentifier=-teddy", 
    "Stage=dev",
    "PlaidSecretsArn=arn:aws:secretsmanager:us-east-1:816069139448:secret:plaid/secrets-9KwgUH",
    "OrumSecretsArn=arn:aws:secretsmanager:us-east-1:816069139448:secret:orum/secrets-JI6xIb",
    "Auth0SecretsArn=arn:aws:secretsmanager:us-east-1:816069139448:secret:auth0/secrets-Zc3U8o",
    "Auth0Domain=zenobia-beta.us.auth0.com",
    "OrumPublicCertificate=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwWkZhcE5GRWlwNG9ZRnA3UVptcQpIYlhyNTJ6Y0tGZWl0UkoyN2JnMkxDejNlajkwU2lIekgycHdaVm9LN3dyU2J3K0c4UWVsaWlpMjZqM3JzaUtyCllmRTBrSUc5TURiRkZDNm9GYnJyaGI1WEVFNmJYbVY5eEtBYmtrSHF0OGtOVHNLb0E5UjBWcExiZDJwTERxMGQKK3FKd1JtWS9xeUVtNno3b1U2WkUzcHF1Z3F1R3I5a2hGMC9tajdXWU9pQUIyQkNSNERqemxGdWdBVjI4Mk1tRwp6b1ZwdGtpVDRjRi9LRTZ5RVBaenI3S3NlMFBKeXozOWtTa0dxbnBpSmsrQjZmZTZtRmVYTlo3M1l3SnJDU281CjV2R05RR2ZmTmZ4OWllbjA3QWU1RnJlZmNMcFB5R3BVcHd6ZlNranNnT21RbHVKTHR1N0c1Z1JDOTNIQnBmUTkKYndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==",
    "OrumIpAddresses=34.232.246.7",
    "OrumSlackWebhook=https://google.com",
    "WebsocketServiceEndpoint=https://transfer-status.zenobiapay.com/update",
    "ZenobiaApiEndpoint=https://4sdynx1kod.execute-api.us-east-1.amazonaws.com/Prod/",
    "PlaidIpAddresses=52.21.26.131,52.21.47.157,52.41.247.19,52.88.82.239",
    "PlaidSlackWebhook=https://hooks.slack.com/services/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",
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
