AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ZenobiaPay Backend

Parameters:
  Stage:
    Type: String
    Description: Stage this code is being deployed to (dev, beta, gamma, prod)
  UniqueIdentifier:
    Type: String
    Default: ""
    Description: Unique identifier to avoid resource naming conflicts. Should only be needed for dev sandbox accounts
  PlaidSecretsArn:
    Type: String
    Description: Plaid secrets manager arn that stores client id and client secret
  OrumSecretsArn:
    Type: String
    Description: Orum secrets manager arn that stores client id and client secret
  Auth0SecretsArn:
    Type: String
    Description: Auth0 secrets manager arn that stores client id and client secret
  Auth0Domain:
    Type: String
    Description: Auth0 domain used for authentication

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/vpc-stack.yml

  TableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/storage-stack.yml
      Parameters:
        Stage: !Ref Stage
        UniqueIdentifier: !Ref UniqueIdentifier

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/lambda-stack.yml
      Parameters:
        SecurityGroupId: !GetAtt VpcStack.Outputs.SecurityGroupId
        SubnetId1: !GetAtt VpcStack.Outputs.PrivateSubnetId1
        SubnetId2: !GetAtt VpcStack.Outputs.PrivateSubnetId2
        BankTableName: !GetAtt TableStack.Outputs.BankTableName
        UserTableName: !GetAtt TableStack.Outputs.UserTableName
        TransferTableName: !GetAtt TableStack.Outputs.TransferTableName
        BankKeyId: !GetAtt TableStack.Outputs.BankKeyId
        TransferKeyId: !GetAtt TableStack.Outputs.TransferKeyId
        UserKeyId: !GetAtt TableStack.Outputs.UserKeyId
        TransferTableStreamArn: !GetAtt TableStack.Outputs.TransferTableStreamArn
        PlaidSecretsArn: !Ref PlaidSecretsArn
        OrumSecretsArn: !Ref OrumSecretsArn
        Auth0SecretsArn: !Ref Auth0SecretsArn
        Auth0Domain: !Ref Auth0Domain

  PayoutStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/payout-stack.yml
      Parameters:
        TransferTableName: !GetAtt TableStack.Outputs.TransferTableName
        UserTableName: !GetAtt TableStack.Outputs.UserTableName
        TransferKeyId: !GetAtt TableStack.Outputs.TransferKeyId
        UserKeyId: !GetAtt TableStack.Outputs.UserKeyId
        OrumSecretsArn: !Ref OrumSecretsArn

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !GetAtt LambdaStack.Outputs.WebEndpoint
