AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ZenobiaPay Backend

Parameters:
  Stage:
    Type: String
    Description: Stage this code is being deployed to (dev, beta, gamma, prod)
  UniqueIdentifier:
    Type: String
    Default: ""
    Description: Unique identifier to avoid resource naming conflicts. Should only be needed for dev sandbox accounts

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/vpc-stack.yml

  TableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/storage-stack.yml
      Parameters:
        Stage: !Ref Stage
        UniqueIdentifier: !Ref UniqueIdentifier

  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/auth-stack.yml
      Parameters:
        SecurityGroupId: !GetAtt VpcStack.Outputs.SecurityGroupId
        SubnetId1: !GetAtt VpcStack.Outputs.PrivateSubnetId1
        SubnetId2: !GetAtt VpcStack.Outputs.PrivateSubnetId2
        UserTableName: !GetAtt TableStack.Outputs.UserTableName
        UserKeyId: !GetAtt TableStack.Outputs.UserKeyId

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/lambda-stack.yml
      Parameters:
        SecurityGroupId: !GetAtt VpcStack.Outputs.SecurityGroupId
        SubnetId1: !GetAtt VpcStack.Outputs.PrivateSubnetId1
        SubnetId2: !GetAtt VpcStack.Outputs.PrivateSubnetId2
        UserPoolArn: !GetAtt AuthStack.Outputs.UserPoolArn
        IdentityPoolId: !GetAtt AuthStack.Outputs.IdentityPoolId
        BankTableName: !GetAtt TableStack.Outputs.BankTableName
        UserTableName: !GetAtt TableStack.Outputs.UserTableName
        TransferTableName: !GetAtt TableStack.Outputs.TransferTableName
        CredentialsTableName: !GetAtt TableStack.Outputs.CredentialsTableName
        BankKeyId: !GetAtt TableStack.Outputs.BankKeyId
        TransferKeyId: !GetAtt TableStack.Outputs.TransferKeyId
        UserKeyId: !GetAtt TableStack.Outputs.UserKeyId
        CredentialsKeyId: !GetAtt TableStack.Outputs.CredentialsKeyId
        TransferTableStreamArn: !GetAtt TableStack.Outputs.TransferTableStreamArn

  PayoutStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/payout-stack.yml
      Parameters:
        UserPoolArn: !GetAtt AuthStack.Outputs.UserPoolArn
        TransferTableName: !GetAtt TableStack.Outputs.TransferTableName

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !GetAtt LambdaStack.Outputs.WebEndpoint
