AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ZenobiaPay Backend

Parameters:
  Stage:
    Type: String
    Description: Stage this code is being deployed to (dev, beta, gamma, prod)
  UniqueIdentifier:
    Type: String
    Default: ""
    Description: Unique identifier to avoid resource naming conflicts. Should only be needed for dev sandbox accounts
  PlaidSecretsArn:
    Type: String
    Description: Plaid secrets manager arn that stores client id and client secret
  OrumSecretsArn:
    Type: String
    Description: Orum secrets manager arn that stores client id and client secret
  Auth0SecretsArn:
    Type: String
    Description: Auth0 secrets manager arn that stores client id and client secret
  Auth0Domain:
    Type: String
    Description: Auth0 domain used for authentication
  OrumPublicCertificate:
    Type: String
    Description: Orum public certificate used for webhook signing
  OrumIpAddresses:
    Type: String
    Description: Valid orum ip addresses to accept requests from. Comma separated.
  OrumSlackWebhook:
    Type: String
    Description: Slack webhook for orum channel
  PlaidIpAddresses:
    Type: String
    Description: Valid plaid ip addresses to accept requests from. Comma separated.
  PlaidSlackWebhook:
    Type: String
    Description: Slack webhook for plaid channel
  WebsocketServiceEndpoint:
    Type: String
    Description: Websocket endpoint to send transfer updates to.
  ZenobiaApiEndpoint:
    Type: String
    Description: Endpoint to api service. In prod this should be https://api.zenobiapay.com/ needed for plaid webhooks
  ResaleServiceEndpoint:
    Type: String
    Description: Endpoint to resale service that automates reselling.

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/vpc-stack.yml

  TableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/storage-stack.yml
      Parameters:
        Stage: !Ref Stage
        UniqueIdentifier: !Ref UniqueIdentifier
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PrivateSubnet1: !GetAtt VpcStack.Outputs.PrivateSubnetId1
        PrivateSubnet2: !GetAtt VpcStack.Outputs.PrivateSubnetId2
        SecurityGroupId: !GetAtt VpcStack.Outputs.SecurityGroupId
        RdsSecurityGroupId: !GetAtt VpcStack.Outputs.RdsSecurityGroupId
  
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./sam/auth-stack.yml

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/lambda-stack.yml
      Parameters:
        Stage: !Ref Stage
        SecurityGroupId: !GetAtt VpcStack.Outputs.SecurityGroupId
        SubnetId1: !GetAtt VpcStack.Outputs.PrivateSubnetId1
        SubnetId2: !GetAtt VpcStack.Outputs.PrivateSubnetId2
        MetadataDBEndpoint: !GetAtt TableStack.Outputs.MetadataDBEndpoint
        MetadataDBPort: !GetAtt TableStack.Outputs.MetadataDBPort
        MetadataDBName: !GetAtt TableStack.Outputs.MetadataDBName
        MetadataDBSecret: !GetAtt TableStack.Outputs.MetadataDBSecret
        MetadataDBKmsKeyArn: !GetAtt TableStack.Outputs.MetadataDBKmsKeyArn
        MetadataDBProxyEndpoint: !GetAtt TableStack.Outputs.MetadataDBProxyEndpoint
        ItemMetadataQueueUrl: !GetAtt ItemMetadataStack.Outputs.ItemMetadataQueueUrl
        CredentialsTableName: !GetAtt TableStack.Outputs.CredentialsTableName
        BankTableName: !GetAtt TableStack.Outputs.BankTableName
        UserTableName: !GetAtt TableStack.Outputs.UserTableName
        TransferTableName: !GetAtt TableStack.Outputs.TransferTableName
        CredentialsTableKeyId: !GetAtt TableStack.Outputs.CredentialsTableKeyId
        BankKeyId: !GetAtt TableStack.Outputs.BankKeyId
        TransferKeyId: !GetAtt TableStack.Outputs.TransferKeyId
        UserKeyId: !GetAtt TableStack.Outputs.UserKeyId
        TransferTableStreamArn: !GetAtt TableStack.Outputs.TransferTableStreamArn
        PlaidSecretsArn: !Ref PlaidSecretsArn
        OrumSecretsArn: !Ref OrumSecretsArn
        Auth0SecretsArn: !Ref Auth0SecretsArn
        Auth0Domain: !Ref Auth0Domain
        OrumPublicCertificate: !Ref OrumPublicCertificate
        OrumIpAddresses: !Ref OrumIpAddresses
        ImageStorageBucketName: !GetAtt TableStack.Outputs.ImageStorageBucketName
        ImageStorageBucketKmsKeyArn: !GetAtt TableStack.Outputs.ImageStorageBucketKmsKeyArn
        OrumSlackWebhook: !Ref OrumSlackWebhook
        PlaidIpAddresses: !Ref PlaidIpAddresses
        PlaidSlackWebhook: !Ref PlaidSlackWebhook
        CustomerJwtSigningSecret: !GetAtt AuthStack.Outputs.CustomerJwtSigningSecret
        RefreshTokenHashingSecret: !GetAtt AuthStack.Outputs.RefreshTokenHashingSecret
        BankAccountHashingSecret: !GetAtt AuthStack.Outputs.BankAccountHashingSecret
        ZenobiaApiEndpoint: !Ref ZenobiaApiEndpoint
        ResaleServiceEndpoint: !Ref ResaleServiceEndpoint
        ResaleSigningSecret: !GetAtt AuthStack.Outputs.ResaleSigningSecret

  PayoutStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/payout-stack.yml
      Parameters:
        TransferTableName: !GetAtt TableStack.Outputs.TransferTableName
        TransferTableStreamArn: !GetAtt TableStack.Outputs.TransferTableStreamArn
        UserTableName: !GetAtt TableStack.Outputs.UserTableName
        TransferKeyId: !GetAtt TableStack.Outputs.TransferKeyId
        UserKeyId: !GetAtt TableStack.Outputs.UserKeyId
        OrumSecretsArn: !Ref OrumSecretsArn
        WebsocketServiceEndpoint: !Ref WebsocketServiceEndpoint

  DashboardStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/dashboard-stack.yml

  ItemMetadataStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sam/item-metadata-stack.yml
      Parameters:
        Stage: !Ref Stage
        SecurityGroupId: !GetAtt VpcStack.Outputs.SecurityGroupId
        RdsSecurityGroupId: !GetAtt VpcStack.Outputs.RdsSecurityGroupId
        SubnetId1: !GetAtt VpcStack.Outputs.PrivateSubnetId1
        SubnetId2: !GetAtt VpcStack.Outputs.PrivateSubnetId2
        MetadataDBProxyEndpoint: !GetAtt TableStack.Outputs.MetadataDBProxyEndpoint
        MetadataDBName: !GetAtt TableStack.Outputs.MetadataDBName
        MetadataDBSecret: !GetAtt TableStack.Outputs.MetadataDBSecret
        MetadataDBKmsKeyArn: !GetAtt TableStack.Outputs.MetadataDBKmsKeyArn
        TransferTableName: !GetAtt TableStack.Outputs.TransferTableName
        ImageStorageBucketName: !GetAtt TableStack.Outputs.ImageStorageBucketName
        ImageStorageBucketKmsKeyArn: !GetAtt TableStack.Outputs.ImageStorageBucketKmsKeyArn

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !GetAtt LambdaStack.Outputs.WebEndpoint
  
  # Database outputs
  MetadataDBEndpoint:
    Description: "PostgreSQL RDS endpoint"
    Value: !GetAtt TableStack.Outputs.MetadataDBEndpoint
  
  MetadataDBPort:
    Description: "PostgreSQL RDS port"
    Value: !GetAtt TableStack.Outputs.MetadataDBPort
  
  MetadataDBName:
    Description: "PostgreSQL RDS database name"
    Value: !GetAtt TableStack.Outputs.MetadataDBName
