[versions]
aws = "2.30.22"
jackson = "2.18.3"
dagger = "2.48"

[libraries]
# AWS BOM
aws-bom = { module = "software.amazon.awssdk:bom", version.ref = "aws" }

# AWS SDK services
aws-secretsmanager = { module = "software.amazon.awssdk:secretsmanager" }
aws-s3 = { module = "software.amazon.awssdk:s3" }
aws-dynamodb = { module = "software.amazon.awssdk:dynamodb" }

# Jackson
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }

# Testing
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
