AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication stack.

Resources:
  CustomerJwtSigningSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: jwt/customer/hmac
      Description: HMAC secret for signing customer jwts
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: secret
        PasswordLength: 64
        ExcludeCharacters: "\"@/\\^`|&[](){}$=+"

  RefreshTokenHashingSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: credentials/refreshtoken/hmac
      Description: HMAC secret for signing customer jwts
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: secret
        PasswordLength: 64
        ExcludeCharacters: "\"@/\\^`|&[](){}$=+"

Outputs:
  CustomerJwtSigningSecret:
    Value: !Ref CustomerJwtSigningSecret
    Description: Signing secret for jwt
  RefreshTokenHashingSecret:
    Value: !Ref RefreshTokenHashingSecret
    Description: Signing secret for refresh tokens
