AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication stack.

Resources:
  CustomerJwtSigningSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Name: jwt/customer/hmac
      Description: HMAC secret for signing customer jwts
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: secret
        PasswordLength: 64
        ExcludeCharacters: "\"@/\\^`|&[](){}$=+"

  RefreshTokenHashingSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Name: credentials/refreshtoken/hmac
      Description: HMAC secret for signing customer jwts
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: secret
        PasswordLength: 64
        ExcludeCharacters: "\"@/\\^`|&[](){}$=+"

  BankAccountHashingSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Name: credentials/bankaccount/hmac
      Description: HMAC secret for hashing bank account
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: secret
        PasswordLength: 64
        ExcludeCharacters: "\"@/\\^`|&[](){}$=+"

  ResaleSigningSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Name: credentials/resale/hmac
      Description: HMAC secret for signing resale requests
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: secret
        PasswordLength: 64
        ExcludeCharacters: "\"@/\\^`|&[](){}$=+"

Outputs:
  CustomerJwtSigningSecret:
    Value: !Ref CustomerJwtSigningSecret
    Description: Signing secret for jwt
  RefreshTokenHashingSecret:
    Value: !Ref RefreshTokenHashingSecret
    Description: Signing secret for refresh tokens
  BankAccountHashingSecret:
    Value: !Ref BankAccountHashingSecret
    Description: Signing secret for bank account
  ResaleSigningSecret:
    Value: !Ref ResaleSigningSecret
    Description: Signing secret for resale requests
