AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack to store DDB tables

Parameters:
  Stage:
    Type: String
    Description: Stage this code is being deployed to (dev, beta, gamma, prod)
  UniqueIdentifier:
    Type: String
    Description: Unique identifier to avoid resource naming conflicts. Should only be needed for dev sandbox accounts

Resources:
  BankKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key to encrypt Bank DynamoDB table
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  BankTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BankTable
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S

      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref BankKmsKey
        SSEType: KMS

  TransferKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key to encrypt Bank DynamoDB table
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  TransferTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TransferTable
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: gsi1Pk
              KeyType: HASH
            - AttributeName: gsi1Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: gsi2Pk
              KeyType: HASH
            - AttributeName: gsi2Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI3
          KeySchema:
            - AttributeName: gsi3Pk
              KeyType: HASH
            - AttributeName: gsi3Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1Pk
          AttributeType: S
        - AttributeName: gsi1Sk
          AttributeType: S
        - AttributeName: gsi2Pk
          AttributeType: S
        - AttributeName: gsi2Sk
          AttributeType: S
        - AttributeName: gsi3Pk
          AttributeType: S
        - AttributeName: gsi3Sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref TransferKmsKey
        SSEType: KMS
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  UserKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key to encrypt Bank DynamoDB table
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserTable
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref UserKmsKey
        SSEType: KMS

Outputs:
  BankKeyId:
    Value: !Ref BankKmsKey
    Description: Bank table that stores plaid credentials
  TransferKeyId:
    Value: !Ref TransferKmsKey
    Description: Bank table that stores plaid credentials
  UserKeyId:
    Value: !Ref UserKmsKey
    Description: Bank table that stores plaid credentials
  BankTableName:
    Value: !Ref BankTable
    Description: Bank table that stores plaid credentials
  TransferTableName:
    Value: !Ref TransferTable
    Description: Transfer table that stores transfer requests and transfer details
  UserTableName:
    Value: !Ref UserTable
    Description: User table that stores additional user metadata
  TransferTableStreamArn:
    Value: !GetAtt TransferTable.StreamArn

