const { BedrockRuntimeClient, InvokeModelCommand } = require('@aws-sdk/client-bedrock-runtime');
const { SQSClient } = require('@aws-sdk/client-sqs');
const { VM } = require('vm2');

// Constants for LLM handling
const LLM_MODEL_ID = 'anthropic.claude-3-sonnet-20240229-v1:0';
const SYSTEM_PROMPT = `
You generalize arbitrary json into a specific format. You are thoughtful and always choose the most appropriate field to map in a way that works generically across similarly structered json fields.

Inputs, two jsons, example and desired
example shows an example structure that you want to generalize
Desired shows the desired json structure, with TODO as its value.
Desired schema JSONs can have comments that describe more in detail what is required of the field.

Output a pure javascript function called transform() that takes the example json and returns json in the desired format. Do not use markdown, do not add additional text.

Rules:
1. OUTPUT SHOULD BE CODE ONLY. Function name should be transform() that takes one json input.
2. Don't use magic indices to find array elements. Use properties within the array to find the correct element.
3. If you cannot find an attribute, leave the field as null.
`;

const DESIRED_SCHEMA = `
{
  name: "TODO", // Name of the item
  brandName: "TODO", // Brand of the item. Nike, Hermes, etc.
  size: "TODO", // Small, Medium, Large, X-Large, etc. Only standard sizes.
  color: "TODO", // Color of the item, red, green, etc.
  material: "TODO", // Material item is made of. Leather, cotton, etc.
  year: "TODO", // Year the item was released.
  imageUrls: ["TODO"] // Array of image URLs. Should be full URLs linking to images of the product. First link should be the main image.
}`;

// Initialize clients
const bedrockClient = new BedrockRuntimeClient();

/**
 * Generate a response from the LLM model
 * @param {string} prompt - The prompt to send to the model
 * @param {string} systemPrompt - The system prompt to guide the model
 * @param {string} modelId - The ID of the model to use
 * @param {number} temperature - The temperature parameter for generation
 * @returns {Promise<string>} - The generated response
 */
async function generateResponse(prompt, systemPrompt, modelId, temperature) {
  try {
    if (!modelId.startsWith('anthropic.claude')) {
      throw new Error(`Unsupported model ID: ${modelId}`);
    }
    
    // Create the request body for Claude
    const requestBody = {
      anthropic_version: 'bedrock-2023-05-31',
      temperature: temperature,
      max_tokens: 4000,  // Setting a large max token limit
      messages: [
        {
          role: 'user',
          content: `${systemPrompt}\n\n${prompt}`
        }
      ]
    };

    const command = new InvokeModelCommand({
      modelId: modelId,
      body: JSON.stringify(requestBody)
    });

    const response = await bedrockClient.send(command);
    const responseBody = JSON.parse(Buffer.from(response.body).toString('utf-8'));
    // Parse the response based on the model
    console.log("Got response body ", responseBody)
    if (modelId.startsWith('anthropic.claude')) {
      if (responseBody.content && responseBody.content.length > 0) {
        return responseBody.content[0].text;
      }
      return '';
    }
    
    return '';
  } catch (error) {
    console.error('Error generating LLM response:', error);
    throw new Error(`Failed to generate LLM response: ${error.message}`);
  }
}

/**
 * Transform item metadata using the LLM
 * @param {Object} metadata - The item metadata to transform
 * @returns {Promise<Object>} - The transformed metadata
 */
async function transformItemMetadata(metadata) {
  const stringMetadata = JSON.stringify(metadata);
  const prompt = `example: ${stringMetadata}\ndesired: ${DESIRED_SCHEMA}`;
  
  console.log('Sending prompt to LLM:', prompt);
  const transformScript = await generateResponse(prompt, SYSTEM_PROMPT, LLM_MODEL_ID, 1.0);
  console.log('Got LLM output:', transformScript);
  
  // Execute the transformation script
  const transformedData = executeTransformScript(transformScript, metadata);
  console.log('Transformed metadata:', JSON.stringify(transformedData));
  
  return transformedData;
}

/**
 * Execute the transformation script generated by the LLM
 * @param {string} transformScript - The JavaScript transformation function
 * @param {Object} metadata - The metadata to transform
 * @returns {Object} - The transformed metadata
 */
function executeTransformScript(transformScript, metadata) {
  try {
    // Create a new VM instance with sandbox
    const vm = new VM({
      timeout: 5000, // 5 second timeout
      sandbox: {}, // Empty sandbox
      eval: false, // Don't allow eval
      wasm: false // Don't allow WebAssembly
    });

    // Run the transform script in the sandbox
    const result = vm.run(`
      ${transformScript}
      
      // Export the result of the transform function
      (function() {
        try {
          return transform(${JSON.stringify(metadata)});
        } catch (err) {
          return { error: err.message };
        }
      })();
    `);

    // Check if there was an error in the transform function
    if (result && result.error) {
      throw new Error(`Transform function error: ${result.error}`);
    }

    return result;
  } catch (error) {
    console.error('Error executing transformation script:', error);
    throw new Error(`Failed to execute transformation script: ${error.message}`);
  }
}

/**
 * Main handler function for the Lambda
 * @param {Object} event - The event object from AWS Lambda
 * @returns {Promise<Object>} - The processing result
 */
exports.handler = async (event) => {
  console.log('Received event:', JSON.stringify(event, null, 2));
  
  try {
      // Transform the item metadata using LLM
      const transformedMetadata = await transformItemMetadata(event);
      
      // Return the transformed metadata directly
      return {
        statusCode: 200,
        body: JSON.stringify({
          transformedMetadata
        })
      };
    } catch (error) {
      console.error('Error processing direct metadata:', error);
      return {
        statusCode: 500,
        body: JSON.stringify({
          error: `Failed to transform metadata: ${error.message}`
        })
      };
    }
}
