name: BetaActions

on:
  push:
    branches: [ "beta" ]
  pull_request:
    branches: [ "beta" ]
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: write    # This is required for gradle dependency graph and git checkout
jobs:
  build-kotlin:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install yq
      run: |
        curl -LJO https://github.com/mikefarah/yq/releases/download/v4.15.1/yq_linux_amd64
        chmod +x yq_linux_amd64
        sudo mv yq_linux_amd64 /usr/local/bin/yq
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build Kotlin artifacts
      run: make kotlin

  build-go:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Go
      run: |
        wget -q https://golang.org/dl/go1.18.5.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.18.5.linux-amd64.tar.gz
        echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
        source ~/.bashrc

    - name: Build Go artifacts
      run: make go

  gradle-dependency-check:
    if: github.event_name == 'push' && github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4

  deploy-beta-tf:
    if: github.event_name == 'push' && github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    environment: beta
    steps:
    - uses: actions/checkout@v4
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::039319543506:role/GithubActionsBeta
        role-session-name: github-actions-${{ github.workflow }}-${{ github.run_id }}
        aws-region: us-east-1
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: |
        terraform init \
        -backend-config="bucket=zenobia-terraform-bucket" \
        -backend-config="key=envs/beta/terraform.tfstate" \
        -backend-config="region=us-east-1"
      working-directory: terraform
    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform
      env:
        TF_VAR_AUTH0_DOMAIN: ${{ vars.TF_VAR_AUTH0_DOMAIN}}
        TF_VAR_AUTH0_CLIENT_ID: ${{ secrets.TF_VAR_AUTH0_CLIENT_ID }}
        TF_VAR_AUTH0_CLIENT_SECRET: ${{ secrets.TF_VAR_AUTH0_CLIENT_SECRET }}
        TF_VAR_AUTH0_ACTION_CLIENT_SECRET: ${{ secrets.TF_VAR_AUTH0_ACTION_CLIENT_SECRET }}
        TF_VAR_ZENOBIA_ENDPOINT: ${{ vars.TF_VAR_ZENOBIA_ENDPOINT}}
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        TF_VAR_AUTH0_DOMAIN: ${{ vars.TF_VAR_AUTH0_DOMAIN}}
        TF_VAR_AUTH0_CLIENT_ID: ${{ secrets.TF_VAR_AUTH0_CLIENT_ID }}
        TF_VAR_AUTH0_CLIENT_SECRET: ${{ secrets.TF_VAR_AUTH0_CLIENT_SECRET }}
        TF_VAR_AUTH0_ACTION_CLIENT_SECRET: ${{ secrets.TF_VAR_AUTH0_ACTION_CLIENT_SECRET }}
        TF_VAR_ZENOBIA_ENDPOINT: ${{ vars.TF_VAR_ZENOBIA_ENDPOINT}}

  deploy-beta:
    if: github.event_name == 'push' && github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    environment: beta
    env:
      AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
      AUTH0_SECRETS_ARN: ${{ vars.AUTH0_SECRETS_ARN }}
      ORUM_SECRETS_ARN: ${{ vars.ORUM_SECRETS_ARN }}
      PLAID_SECRETS_ARN: ${{ vars.PLAID_SECRETS_ARN }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - uses: aws-actions/setup-sam@v2
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      with:
        role-to-assume: arn:aws:iam::045667251056:role/GithubActionsDeploymentRole
        role-session-name: github-actions-${{ github.workflow }}-${{ github.run_id }}
        aws-region: us-east-1

    - name: Install Go
      run: |
        wget -q https://golang.org/dl/go1.18.5.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.18.5.linux-amd64.tar.gz
        echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
        source ~/.bashrc

    - name: Install yq
      run: |
        curl -LJO https://github.com/mikefarah/yq/releases/download/v4.15.1/yq_linux_amd64
        chmod +x yq_linux_amd64
        sudo mv yq_linux_amd64 /usr/local/bin/yq
    - name: Build Go artifacts
      run: make go
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build Kotlin artifacts
      run: make kotlin
    - name: Deploy sam
      run: |
        sam deploy --no-confirm-changeset \
          --parameter-overrides \
          Stage=beta \
          PlaidSecretsArn=$PLAID_SECRETS_ARN \
          OrumSecretsArn=$ORUM_SECRETS_ARN \
          Auth0SecretsArn=$AUTH0_SECRETS_ARN \
          Auth0Domain=$AUTH0_DOMAIN
