name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Go
      run: |
        wget -q https://golang.org/dl/go1.18.5.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.18.5.linux-amd64.tar.gz
        echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
        source ~/.bashrc

    - name: Install yq
      run: |
        curl -LJO https://github.com/mikefarah/yq/releases/download/v4.15.1/yq_linux_amd64
        chmod +x yq_linux_amd64
        sudo mv yq_linux_amd64 /usr/local/bin/yq

    - name: Build Go artifacts
      run: make go

    - name: Build Kotlin artifacts
      run: make kotlin
